Decoding Sensefarm with test case associated
diwise/iot-agent pull request #20
Opened 2022-09-01 15:50 UTC by mats-dahlberg-goteborg

2022-09-02 15:19 UTC, istyf requested changes
Det finns några saker som behöver åtgärdas innan vi kan merga detta. Jag skulle även vilja att du pekar ut develop som målbranch först, så kan vi merga därifrån till main sedan.

2022-09-02 15:19 UTC, istyf commented on internal/pkg/application/decoder/decoders.sensefarm.go
> +				fmt.Println("0x01 = ", byteValue)
Inga ostrukturerade utskrifter till konsollen i main (gäller samtliga case).

2022-09-02 15:19 UTC, istyf commented on internal/pkg/application/decoder/decoders.sensefarm.go
> +func byteToValue(b []byte, pos int, number_of_bytes int) uint64 {
Se kommentar på rad 139.

2022-09-02 15:19 UTC, istyf commented on internal/pkg/application/decoder/decoders_test.go
> +	  "devEui":"70b3d554600002b0",
Det här ser ut som ett riktigt devEui. En bra regel kan vara att obfuskera dessa i vårt testdata.

2022-09-02 15:19 UTC, istyf commented on internal/pkg/application/decoder/decoders_test.go
> +	is.Equal(r.Timestamp, "2022-08-25T06:40:56.785171Z")
Jag vet att vi slarvar friskt i andra tester, men vi borde egentligen kosta på oss någon mer assert än så här. :)

2022-09-02 15:19 UTC, istyf commented on internal/pkg/application/decoder/decoders.sensefarm.go
> +	Resistance         []uint64 // 0 -> 4294967295 Ohm
Pet peeve, men något som kan itereras över borde inte ha ett namn som antyder att det bara är ett värde. Samma gäller för SoilMoisture nedan.

2022-09-11 18:55 UTC, istyf reviewed
Ser att det finns en till PR så jag skall kika på den också.

2022-09-11 18:55 UTC, istyf commented on internal/pkg/application/decoder/decoders.sensefarm.go
>  	}
En tom input array borde kanske generera ett fel här och inte bara tyst rinna igenom?

2022-09-11 18:55 UTC, istyf commented on internal/pkg/application/decoder/decoders.sensefarm.go
> +				return err
Här (och i efterföljande case) kan det vara en idé att dekorera det err som returneras med lite info om vad som försökte göras. Tex err = fmt.Errorf("failed to read temperature: %w", err)

2022-09-11 18:55 UTC, istyf commented on internal/pkg/application/decoder/decoders.sensefarm.go
> +			var tempInt32 int32
var resistance int32 vore snyggare här. temp är förvillande likt temperature och att ha typen i variabelnamnet är ganska onödigt. Gäller även följande case.

2022-09-12 13:31 UTC, closed without merging

2022-09-12 13:31 UTC, mats-dahlberg-goteborg commented
Fel miljö